### ISSUE TITLE
Responsive ListItems

### ISSUE THREAD

**Issue by ChetCorey** [ChetCorey/duke-data-service-portal#4]
- ListItems is responsive to ScreenSize and not Container width making it behave poorly in Dashboard with TreeList Open

![responsivelistitemsbug itemactionbuttionsbug breadcrumbwrappingbug](https://user-images.githubusercontent.com/7772027/38633643-4d1fb938-3d8e-11e8-8524-653f85bf036d.gif)

**Comment by caseychoiniere** [comment]
What screen size are you testing this on? I thought that you had decided to disable the dashboard link in the menu on smaller screens? Is this behavior happening because you're resizing your screen after navigating to the dashboard? When I view the dashboard on my screen it looks good all the way up to the point that the dashboard link disappears from the left nav menu.

**Comment by ChetCorey** [comment]
"Is this behavior happening because you're resizing your screen after navigating to the dashboard?"
Yes
"When I view the dashboard on my screen it looks good all the way up to the point that the dashboard link disappears from the left nav menu."
You are correct, I will drop this issue/bug.

**Comment by ChetCorey** [comment]
"Is this behavior happening because you're resizing your screen after navigating to the dashboard?"
Yes
"When I view the dashboard on my screen it looks good all the way up to the point that the dashboard link disappears from the left nav menu."
You are correct, I will drop this issue/bug.
